name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use a versão de Python que seu projeto exige

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de ter esse arquivo com as dependências do Python

      - name: Run Pylint
        run: pylint src/python/**/*.py  # Ajuste se necessário o caminho dos arquivos Python

      - name: Run tests
        run: |
          pytest  # Assumindo que você tenha o pytest configurado para testes